apiVersion: v1
kind: Service
metadata:
  name: station-session-cache
  labels:
    run: station-session-cache
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: station-session-cache
